######################################################################
# Automatically generated by qmake (2.01a) Fr Feb 8 22:06:01 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
