#!/bin/sh
if [ -e test.cvsroot ]
then
  echo "Test CVS root Directory already there."
  exit 1
fi
mkdir test.cvsroot || exit 1
CVSROOT=$PWD/test.cvsroot
cvs -d $CVSROOT init

if [ -e test.cvstemp ]
then
  echo "Test CVS temp Directory already there."
  exit 1
fi
mkdir test.cvstemp || exit 1
mkdir test.cvstemp/import || exit 1
cd $CVSROOT/../test.cvstemp/import
echo "initial import" >A
cvs -d $CVSROOT import -m "initial import" test vendor_tag initial_import 

cd $CVSROOT/../test.cvstemp
cvs -d $CVSROOT co test
cd test
echo "file added" >B
cvs add B
sleep 2
cvs ci -m "B added"

cvs delete -f A
sleep 2
cvs ci -m "A removed"

echo "something different" >B
sleep 2
cvs ci -m "B changed"

mkdir dir
cvs add dir
echo "some subdir" > dir/D
cvs add dir/D
sleep 2
cvs ci -m "dir/D added"

echo "revived" >A
cvs add A
sleep 2
cvs ci -m "A readded"

