#!/bin/sh
if [ -e test.cvsroot ]
then
  echo "Test CVS root Directory already there."
  exit 1
fi
mkdir test.cvsroot || exit 1
CVSROOT=$PWD/test.cvsroot
cvs -Q -d $CVSROOT init

if [ -e test.cvstemp ]
then
  echo "Test CVS temp Directory already there."
  exit 1
fi
mkdir test.cvstemp || exit 1
mkdir test.cvstemp/import || exit 1
cd $CVSROOT/../test.cvstemp/import
echo "initial import" >A
echo "initial "`date` `TZ=UTC date` `date +%s`
cvs -Q -d $CVSROOT import -m "initial import" test vendor_tag initial_import 

if [ "$1" = "import" ] 
then 
  cd $CVSROOT/..
  rm -rf test.cvstemp || exit 1
  exit 0 
fi

cd $CVSROOT/../test.cvstemp
cvs -Q -d $CVSROOT co test
cd test
echo "file added" >B
cvs -Q add B
sleep 1
cvs -Q ci -m "B added"

cvs -Q delete -f A
sleep 1
cvs -Q ci -m "A removed"

echo "something different" >B
sleep 1
cvs -Q ci -m "B changed"

mkdir dir
cvs -Q add dir
echo "some subdir" > dir/D
cvs -Q add dir/D
sleep 1
cvs -Q ci -m "dir/D added"

echo "revived" >A
cvs -Q add A
sleep 1
cvs -Q ci -m "A readded"

cd $CVSROOT/..
rm -rf test.cvstemp || exit 1
