#!/bin/sh
if [ ! -e test.cvsroot ]
then
  echo "Test CVS root Directory not already there."
  exit 1
fi
CVSROOT=$PWD/test.cvsroot

if [ -e test.cvstemp ]
then
  echo "Test CVS working Directory already there."
  exit 1
fi

mkdir test.cvstemp
cd test.cvstemp
cvs -Q -d $CVSROOT co test
cd test

# rapidly check in with different logs to check the merge algorithm
echo "fast A" >A
echo "fast C" >dir/C
echo "fast D" >dir/D
cvs -Q add A
sleep 1
cvs -Q ci -m "fast A change" A
cvs -Q ci -m "fast C change" dir/C
cvs -Q ci -m "fast D change" dir/D

cd $CVSROOT/..
rm -rf test.cvstemp || exit 1
