#!/bin/sh
if [ ! -e test.cvsroot ]
then
  echo "Test CVS root Directory not already there."
  exit 1
fi
CVSROOT=$PWD/test.cvsroot

if [ -e test.cvstemp ]
then
  echo "Test CVS working Directory already there."
  exit 1
fi

mkdir $CVSROOT/test2
echo >>$CVSROOT/CVSROOT/modules test1 test
echo >>$CVSROOT/CVSROOT/modules test3 test2 &test1

mkdir test.cvstemp
cd test.cvstemp
cvs -d $CVSROOT co test2
cd test2

echo >AA initial AA
cvs add AA
cvs ci -m "AA added"

mkdir sub2
cvs add sub2
echo >sub2/BB initial BB
cvs add sub2/BB
cvs ci -m "sub2/BB added"

echo >test1/A cross module change
cvs ci -m "cross module change of A"

cd $CVSROOT/..
rm -rf test.cvstemp || exit 1
