#!/bin/sh
if [ ! -e test.cvsroot ]
then
  echo "Test CVS root Directory not already there."
  exit 1
fi
CVSROOT=$PWD/test.cvsroot

if [ -e test.cvstemp ]
then
  echo "Test CVS working Directory already there."
  exit 1
fi

mkdir test.cvstemp
cd test.cvstemp
cvs -d $CVSROOT co test
cd test

echo "and now change D" >dir/D
sleep 2
cvs ci -m "D changed"

cvs delete -f B
sleep 2
cvs ci -m "B remove"

echo "and now add C" >dir/C
cvs add dir/C
sleep 2
cvs ci -m "C added"

cd $CVSROOT/..
rm -rf test.cvstemp || exit 1
