#!/bin/sh
if [ ! -e test.cvsroot ]
then
  echo "Test CVS root Directory not already there."
  exit 1
fi
CVSROOT=$PWD/test.cvsroot

if [ -e test.cvstemp ]
then
  echo "Test CVS working Directory already there."
  exit 1
fi

mkdir test.cvstemp
cd test.cvstemp
cvs -Q -d $CVSROOT co test
cd test

echo "and now change D" >dir/D
sleep 1
cvs -Q ci -m "D changed"

cvs -Q delete -f B
sleep 1
cvs -Q ci -m "B remove"

echo "and now add C" >dir/C
cvs -Q add dir/C
sleep 1
cvs -Q ci -m "C added"

cd $CVSROOT/..
rm -rf test.cvstemp || exit 1
