#!/bin/sh
if [ ! -e test.cvsroot ]
then
  echo "Test CVS root Directory not already there."
  exit 1
fi
CVSROOT=$PWD/test.cvsroot

if [ -e test.cvstemp ]
then
  echo "Test CVS working Directory already there."
  exit 1
fi

mkdir test.cvstemp
cd test.cvstemp
cvs -Q -d $CVSROOT co test
cd test

echo "yet another change" >B
echo "yet another change" >A
sleep 1
cvs -Q ci -m "A+B changed 2"

sleep 1
cvs -Q ci -m "B changed 2"

echo "yet another change 2" >B
sleep 1
cvs -Q ci -m "B changed 3"

cd $CVSROOT/..
rm -rf test.cvstemp || exit 1
