#!/bin/sh
if [ ! -f test.db ]
then
  echo "Test monotone DB not there."
  exit 1
fi
if [ -e test.mt ]
then
  echo "Test monotone checkout directory already there."
  exit 1
fi
../monotone --branch test --db test.db checkout test.mt

cd test.mt

echo "added by monotone" >dir/E
../../monotone add dir/E
echo "The password is 'x'"
../../monotone --key test@localhost --branch test --db ../test.db commit \
	--message "dir/E added"

echo "changed by monotone" >dir/C
sleep 2
../../monotone --key test@localhost --branch test --db ../test.db commit \
	--message "dir/C changed"

../../monotone drop A
sleep 2
../../monotone --key test@localhost --branch test --db ../test.db commit \
	--message "A removed"

