#!/bin/sh
if [ ! -f test.db ]
then
  echo "Test monotone DB not there."
  exit 1
fi
if [ -e test.mt ]
then
  echo "Test monotone checkout directory already there."
  exit 1
fi
../monotone --branch test --db test.db checkout test.mt || exit

cd test.mt

echo "added by monotone" >dir/E
../../monotone add dir/E || exit
../../monotone --key test@localhost --branch test --db ../test.db commit \
	--message "dir/E added" << EOF
x
EOF
if [ $? -ne 0 ] ; then exit ; fi

echo "changed by monotone" >dir/C
sleep 1
../../monotone --key test@localhost --branch test --db ../test.db commit \
	--message "dir/C changed" << EOF
x
EOF
if [ $? -ne 0 ] ; then exit ; fi

../../monotone drop A
sleep 1
../../monotone --key test@localhost --branch test --db ../test.db commit \
	--message "A removed" << EOF
x
EOF
if [ $? -ne 0 ] ; then exit ; fi
