#!/bin/sh
./cleanup
echo ----------------------------------
echo full checkin
./cvs_test_setup
./cvs_test_setup2
./cvs_test_setup3
./db_setup

echo ----------------------------------
echo incremental update
./cleanup
./cvs_test_setup import
./db_setup
rm -rf  test.cvsroot
./cvs_test_setup 
../monotone --branch test --key test@localhost --db test.db cvs_pull \
        $PWD/test.cvsroot test <<EOF
x
EOF
./cvs_test_setup2
../monotone --branch test --key test@localhost --db test.db cvs_pull \
        $PWD/test.cvsroot test <<EOF
x
EOF
./cvs_test_setup3
../monotone --branch test --key test@localhost --db test.db cvs_pull \
        $PWD/test.cvsroot test <<EOF
x
EOF

echo ---------------------------------
echo done
